`define IF_TO_ID_WD 64
`define ID_TO_IF_WD 34
`define ID_TO_EXE_WD 175
`define EXE_TO_MEM_WD 156
`define MEM_TO_WB_WD 70
`define WB_TO_ID_WD 39
`define EXE_TO_ID_WD 41
`define MEM_TO_ID_WD 39
`define MEM_TO_CSR_WD 110
`define CSR_TO_MEM_WD 128
`define MEM_TO_IF_WD 2
`define CSR_TO_IF_WD 64