# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Projects/Studying/LA/CPU_design/readygo/mycpu_env/soc_verify/soc_bram/rtl/xilinx_ip/inst_ram/inst_ram.xci
# IP: The module: 'inst_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Projects/Studying/LA/CPU_design/readygo/mycpu_env/soc_verify/soc_bram/rtl/xilinx_ip/inst_ram/inst_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'inst_ram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/Projects/Studying/LA/CPU_design/readygo/mycpu_env/soc_verify/soc_bram/rtl/xilinx_ip/inst_ram/inst_ram.xci
# IP: The module: 'inst_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Projects/Studying/LA/CPU_design/readygo/mycpu_env/soc_verify/soc_bram/rtl/xilinx_ip/inst_ram/inst_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'inst_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
