# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ysxashore/Data_DISK/Projects/Studying/LoongArch-Learn/CPU_design/cdp_ede_local/mycpu_env/soc_verify/soc_bram/rtl/xilinx_ip/data_ram/data_ram.xci
# IP: The module: 'data_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ysxashore/Data_DISK/Projects/Studying/LoongArch-Learn/CPU_design/cdp_ede_local/mycpu_env/soc_verify/soc_bram/rtl/xilinx_ip/data_ram/data_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_ram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/ysxashore/Data_DISK/Projects/Studying/LoongArch-Learn/CPU_design/cdp_ede_local/mycpu_env/soc_verify/soc_bram/rtl/xilinx_ip/data_ram/data_ram.xci
# IP: The module: 'data_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ysxashore/Data_DISK/Projects/Studying/LoongArch-Learn/CPU_design/cdp_ede_local/mycpu_env/soc_verify/soc_bram/rtl/xilinx_ip/data_ram/data_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
