# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: E:/Projects/Studying/LA/CPU_design/readygo/mycpu_env/module_verify/cache_verify/run_vivado/constraints/cache_top.xdc

# IP: ip/tagv_way1/tagv_way1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tagv_way1 || ORIG_REF_NAME==tagv_way1} -quiet] -quiet

# IP: ip/data_way1_bank3/data_way1_bank3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==data_way1_bank3 || ORIG_REF_NAME==data_way1_bank3} -quiet] -quiet

# IP: ip/data_way1_bank2/data_way1_bank2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==data_way1_bank2 || ORIG_REF_NAME==data_way1_bank2} -quiet] -quiet

# IP: ip/data_way1_bank1/data_way1_bank1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==data_way1_bank1 || ORIG_REF_NAME==data_way1_bank1} -quiet] -quiet

# IP: ip/data_way1_bank0/data_way1_bank0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==data_way1_bank0 || ORIG_REF_NAME==data_way1_bank0} -quiet] -quiet

# IP: ip/data_way0_bank3/data_way0_bank3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==data_way0_bank3 || ORIG_REF_NAME==data_way0_bank3} -quiet] -quiet

# IP: ip/data_way0_bank2/data_way0_bank2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==data_way0_bank2 || ORIG_REF_NAME==data_way0_bank2} -quiet] -quiet

# IP: ip/data_way0_bank1/data_way0_bank1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==data_way0_bank1 || ORIG_REF_NAME==data_way0_bank1} -quiet] -quiet
