`define IF_TO_ID_WD 65
`define ID_TO_IF_WD 34
`define ID_TO_EXE_WD 183
`define EXE_TO_MEM_WD 165
`define MEM_TO_WB_WD 70
`define WB_TO_ID_WD 71
`define EXE_TO_ID_WD 41
`define MEM_TO_ID_WD 72
`define MEM_TO_CSR_WD 143
`define CSR_TO_MEM_WD 128
`define MEM_TO_IF_WD 2
`define CSR_TO_IF_WD 64