# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ysxashore/Data_DISK/Projects/Studying/LoongArch-Learn/CPU_design/cdp_ede_local_LA_readygo/mycpu_env/soc_verify/soc_axi/run_vivado/project/loongson.srcs/sources_1/ip/inst_tagv_way1/inst_tagv_way1.xci
# IP: The module: 'inst_tagv_way1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ysxashore/Data_DISK/Projects/Studying/LoongArch-Learn/CPU_design/cdp_ede_local_LA_readygo/mycpu_env/soc_verify/soc_axi/run_vivado/project/loongson.gen/sources_1/ip/inst_tagv_way1/inst_tagv_way1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'inst_tagv_way1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/ysxashore/Data_DISK/Projects/Studying/LoongArch-Learn/CPU_design/cdp_ede_local_LA_readygo/mycpu_env/soc_verify/soc_axi/run_vivado/project/loongson.srcs/sources_1/ip/inst_tagv_way1/inst_tagv_way1.xci
# IP: The module: 'inst_tagv_way1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ysxashore/Data_DISK/Projects/Studying/LoongArch-Learn/CPU_design/cdp_ede_local_LA_readygo/mycpu_env/soc_verify/soc_axi/run_vivado/project/loongson.gen/sources_1/ip/inst_tagv_way1/inst_tagv_way1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'inst_tagv_way1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
