# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Projects/Studying/LA/LA32R_GD/chiplab/IP/xilinx_ip/2019.2/dpram_512x32/dpram_512x32.xci
# IP: The module: 'dpram_512x32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Projects/Studying/LA/LA32R_GD/chiplab/IP/xilinx_ip/2019.2/dpram_512x32/dpram_512x32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpram_512x32'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/Projects/Studying/LA/LA32R_GD/chiplab/IP/xilinx_ip/2019.2/dpram_512x32/dpram_512x32.xci
# IP: The module: 'dpram_512x32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Projects/Studying/LA/LA32R_GD/chiplab/IP/xilinx_ip/2019.2/dpram_512x32/dpram_512x32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpram_512x32'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
