# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Projects/Studying/LA/LA32R_GD/chiplab/IP/xilinx_ip/2019.2/clk_pll_33/clk_pll_33.xci
# IP: The module: 'clk_pll_33' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Projects/Studying/LA/LA32R_GD/chiplab/IP/xilinx_ip/2019.2/clk_pll_33/clk_pll_33_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pll_33'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Projects/Studying/LA/LA32R_GD/chiplab/IP/xilinx_ip/2019.2/clk_pll_33/clk_pll_33.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pll_33'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Projects/Studying/LA/LA32R_GD/chiplab/IP/xilinx_ip/2019.2/clk_pll_33/clk_pll_33_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pll_33'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/Projects/Studying/LA/LA32R_GD/chiplab/IP/xilinx_ip/2019.2/clk_pll_33/clk_pll_33.xci
# IP: The module: 'clk_pll_33' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Projects/Studying/LA/LA32R_GD/chiplab/IP/xilinx_ip/2019.2/clk_pll_33/clk_pll_33_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pll_33'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Projects/Studying/LA/LA32R_GD/chiplab/IP/xilinx_ip/2019.2/clk_pll_33/clk_pll_33.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pll_33'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Projects/Studying/LA/LA32R_GD/chiplab/IP/xilinx_ip/2019.2/clk_pll_33/clk_pll_33_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pll_33'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
