# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Download/Chiplab/chiplab_env/IP/myCPU/IP/tagv_sram/tagv_sram.xci
# IP: The module: 'tagv_sram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Download/Chiplab/chiplab_env/IP/myCPU/IP/tagv_sram/tagv_sram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tagv_sram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/Download/Chiplab/chiplab_env/IP/myCPU/IP/tagv_sram/tagv_sram.xci
# IP: The module: 'tagv_sram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Download/Chiplab/chiplab_env/IP/myCPU/IP/tagv_sram/tagv_sram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tagv_sram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
