# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Projects/Studying/LA/LA32R_GD/chiplab/IP/xilinx_ip/2019.2/axi_clock_converter_0/axi_clock_converter_0/axi_clock_converter_0.xci
# IP: The module: 'axi_clock_converter_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Projects/Studying/LA/LA32R_GD/chiplab/IP/xilinx_ip/2019.2/axi_clock_converter_0/axi_clock_converter_0/axi_clock_converter_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_clock_converter_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Projects/Studying/LA/LA32R_GD/chiplab/IP/xilinx_ip/2019.2/axi_clock_converter_0/axi_clock_converter_0/axi_clock_converter_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_clock_converter_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/Projects/Studying/LA/LA32R_GD/chiplab/IP/xilinx_ip/2019.2/axi_clock_converter_0/axi_clock_converter_0/axi_clock_converter_0.xci
# IP: The module: 'axi_clock_converter_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Projects/Studying/LA/LA32R_GD/chiplab/IP/xilinx_ip/2019.2/axi_clock_converter_0/axi_clock_converter_0/axi_clock_converter_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_clock_converter_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Projects/Studying/LA/LA32R_GD/chiplab/IP/xilinx_ip/2019.2/axi_clock_converter_0/axi_clock_converter_0/axi_clock_converter_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_clock_converter_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
