# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: E:/Projects/Studying/LA/LA32R_GD/chiplab/fpga/loongson/soc_up.xdc

# IP: E:/Projects/Studying/LA/LA32R_GD/chiplab/IP/myCPU/IP/tagv_sram/tagv_sram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tagv_sram || ORIG_REF_NAME==tagv_sram} -quiet] -quiet

# IP: E:/Projects/Studying/LA/LA32R_GD/chiplab/IP/myCPU/IP/data_bank_sram/data_bank_sram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==data_bank_sram || ORIG_REF_NAME==data_bank_sram} -quiet] -quiet
