# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ysxashore/Data_DISK/Projects/Studying/LoongArch-Learn/CPU_design/cdp_ede_local_LA_readygo/mycpu_env/module_verify/cache_verify/run_vivado/project/loongson.srcs/sources_1/ip/tagv_way0/tagv_way0.xci
# IP: The module: 'tagv_way0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ysxashore/Data_DISK/Projects/Studying/LoongArch-Learn/CPU_design/cdp_ede_local_LA_readygo/mycpu_env/module_verify/cache_verify/run_vivado/project/loongson.gen/sources_1/ip/tagv_way0/tagv_way0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tagv_way0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/ysxashore/Data_DISK/Projects/Studying/LoongArch-Learn/CPU_design/cdp_ede_local_LA_readygo/mycpu_env/module_verify/cache_verify/run_vivado/project/loongson.srcs/sources_1/ip/tagv_way0/tagv_way0.xci
# IP: The module: 'tagv_way0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ysxashore/Data_DISK/Projects/Studying/LoongArch-Learn/CPU_design/cdp_ede_local_LA_readygo/mycpu_env/module_verify/cache_verify/run_vivado/project/loongson.gen/sources_1/ip/tagv_way0/tagv_way0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tagv_way0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
